apiVersion: v1
kind: Secret
metadata:
  name: drupal-db-credentials
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "d5Fep8eq9B1croye$4vEquglvUflc7e9akon0wes"
  MYSQL_DATABASE: "drupal_database"
  MYSQL_USER: "drupal_user"
  MYSQL_PASSWORD: "VoyechuPhiTr94rafRudrEW$pru1i03k4be8r_sw"