apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: drupal
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/target: "5bf6bf0d-fe5a-40fc-adf1-887f866992e3.cfargotunnel.com"
spec:
  virtualhost:
    fqdn: drupal.glauciolabs.work
  routes:
    - conditions:
        - prefix: /
      services:
        - name: drupal
          port: 80
