apiVersion: v1
kind: Secret
metadata:
  name: drupal-db-credentials
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "drupal_root_pass_change_me"
  MYSQL_DATABASE: "drupal"
  MYSQL_USER: "drupal"
  MYSQL_PASSWORD: "drupal_pass_change_me"